version: "3.9"
name: "hjemmeside"

services:
  frontend:
    image: spedsbjerg/spedsbjergwebsite:latest
    restart: always
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    depends_on:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300